export interface PetAction {
  id: string
  label: string
  description: string
  preview?: string
}

export interface PetAuthor {
  id: string
  name: string
  handle: string
  role: string
  bio: string
  badge: string
  badgeColor: string
  initial: string
  bannerGradient: string
  followers: number
  likes: number
  tags: string[]
  acceptCustom: boolean
  customNotice?: string
}

export const galleryAuthors: Record<string, PetAuthor> = {
  official: {
    id: 'official',
    name: 'WindowPet 创研所',
    handle: '@WindowPet_Dev',
    role: '核心看板研发组',
    bio: 'WindowPet 官方核心伙伴设计团队，专注于原生高帧率交互、系统级轻量占用与温暖桌面陪伴。',
    badge: '核心主理',
    badgeColor: '#2563eb',
    initial: '创',
    bannerGradient: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 50%, #60a5fa 100%)',
    followers: 8640,
    likes: 35200,
    tags: ['核心看板', '29帧高刷', '原生交互', '官方质保'],
    acceptCustom: false,
    customNotice: '官方开源看板团队，持续打磨软件基础框架与核心功能',
  },
  mino: {
    id: 'mino',
    name: '米诺画画中',
    handle: '@MinoPixel',
    role: '独立家宠像素插画师',
    bio: '专注真实家养猫狗生活照写生创作，首创 25 帧深度视线转头跟随系列。资深猫狗双全铲屎官。',
    badge: '家宠写生',
    badgeColor: '#059669',
    initial: '米',
    bannerGradient: 'linear-gradient(135deg, #0f766e 0%, #0d9488 50%, #2dd4bf 100%)',
    followers: 5320,
    likes: 22800,
    tags: ['真实毛孩子', '25帧视线跟随', '治愈手绘', '猫犬专精'],
    acceptCustom: true,
    customNotice: '支持生活照私宠 1 对 1 定制约稿（工期约 2~4 天）',
  },
  hoshino: {
    id: 'hoshino',
    name: '星野光年漫研所',
    handle: '@HoshinoAnime',
    role: '动漫概念与插画师',
    bio: '沉迷萌系动漫美术与灵动动作设计，擅长细腻的神态抓取与合奏表演动画，作品风格元气治愈。',
    badge: '动漫插画',
    badgeColor: '#7c3aed',
    initial: '星',
    bannerGradient: 'linear-gradient(135deg, #5b21b6 0%, #7c3aed 50%, #a78bfa 100%)',
    followers: 6180,
    likes: 27900,
    tags: ['动漫萌友', '元气治愈', '乐器合奏', '高帧表演'],
    acceptCustom: true,
    customNotice: '接二次元拟人与专属桌面合奏演出约稿（每月限量 5 单）',
  },
  wildspirit: {
    id: 'wildspirit',
    name: '自然漫步客',
    handle: '@WildSpirit',
    role: '自然生灵手绘客',
    bio: '热爱大自然中的治愈生灵，把水豚卡皮巴拉、热带小鸟和呆萌树懒带到你的电脑边，感受大自然的松弛感。',
    badge: '自然手绘',
    badgeColor: '#0891b2',
    initial: '自',
    bannerGradient: 'linear-gradient(135deg, #0369a1 0%, #0284c7 50%, #38bdf8 100%)',
    followers: 4210,
    likes: 19500,
    tags: ['卡皮巴拉', '自然生灵', '松弛感', '静音陪伴'],
    acceptCustom: false,
    customNotice: '自然动物写生系列持续创作更新中',
  },
  memelab: {
    id: 'memelab',
    name: '整活大队 MemeLab',
    handle: '@MemeLab_UP',
    role: '幽默动态设计师',
    bio: '专注把互联网快乐源泉做成桌面搭子！疯狂敲键盘猫、摸鱼滑稽狗头，专治枯燥上班时间。',
    badge: '趣味动态',
    badgeColor: '#ea580c',
    initial: 'M',
    bannerGradient: 'linear-gradient(135deg, #c2410c 0%, #ea580c 50%, #fb923c 100%)',
    followers: 9450,
    likes: 42100,
    tags: ['打工怨种', '疯狂敲键盘', '无厘头整活', '摸鱼搭子'],
    acceptCustom: true,
    customNotice: '接趣味表情包定制（随缘接单，灵感优先）',
  },
  chestnut: {
    id: 'chestnut',
    name: '糖炒栗子定制工坊',
    handle: '@ChestnutStudio',
    role: '特邀爱宠定制主理人',
    bio: '专注 1 对 1 真实毛发质感建模与微表情设计，代表作【麦脆角摇头猫】，致力于让爱宠长久陪伴你。',
    badge: '特邀定制',
    badgeColor: '#db2777',
    initial: '栗',
    bannerGradient: 'linear-gradient(135deg, #be123c 0%, #e11d48 50%, #fb7185 100%)',
    followers: 4890,
    likes: 21300,
    tags: ['真实毛发', '微表情神态', '猫犬双全', '高端定制'],
    acceptCustom: true,
    customNotice: '特邀定制通道开放中，提供生活照即可量身手绘定制（工期约 3~5 天）',
  },
}

export interface GalleryPet {
  id: string
  name: string
  enName: string
  folderName: string
  code: string
  price: number // 0 为免费，>0 为付费价格（元）
  salesCount: number
  category: 'official' | 'home' | 'anime' | 'nature' | 'fun'
  categoryLabel: string
  authorId: 'official' | 'mino' | 'hoshino' | 'wildspirit' | 'memelab' | 'chestnut'
  authorName: string
  authorHandle: string
  workType: '核心原创' | '家宠写生' | '动漫插画' | '自然生灵' | '趣味动态' | '特邀定制'
  license: string
  tagline: string
  description: string
  mood: string
  traits: string[]
  image: string
  animatedWebp?: string
  redeemCode: string
  canvas: string
  actionCount: number
  actions: PetAction[]
  stats: [string, string][]
  downloadUrl?: string
}

export const galleryCategories = [
  { id: 'all', label: '全部作品', count: 21, icon: 'layers' },
  { id: 'home', label: '治愈毛孩子', count: 5, icon: 'home' },
  { id: 'anime', label: '动漫萌伴', count: 4, icon: 'sparkles' },
  { id: 'nature', label: '森林与生灵', count: 4, icon: 'feather' },
  { id: 'fun', label: '趣味整活', count: 4, icon: 'smile' },
  { id: 'official', label: '创研看板', count: 4, icon: 'award' },
] as const

export const galleryPets: GalleryPet[] = [
  // ----------------- 官方原创组 (@WindowPet 创研所) -----------------
  {
    id: 'jiyi',
    name: '吉伊',
    enName: 'Jiyi',
    folderName: 'JiyiPet',
    code: '0006',
    price: 0,
    salesCount: 8920,
    category: 'official',
    categoryLabel: '创研看板',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '核心原创',
    license: 'WindowPet 原生开源协议',
    tagline: '“今天也是元气满满的一天！打开电脑先挥挥手打个招呼吧~”',
    description: '吉伊是 WindowPet 的核心原创看板伙伴，拥有全场最丰富的动作生态。她会用害羞、跳跃、小鞠躬和合奏哼唱回应你的每一次点击与拖拽，在桌面边沿还会偷偷探头！',
    mood: '活泼 / 亲近 / 萌系元气',
    traits: ['合奏哼唱', '边缘爬行', '超多害羞动作', '全场景互动'],
    image: 'pets/jiyi.png',
    animatedWebp: 'pets/jiyi-animated.webp',
    redeemCode: 'WPX-2026-JIYI',
    canvas: '192x208',
    actionCount: 29,
    stats: [
      ['29 种', '动作生态'],
      ['免费', '开箱可用'],
      ['热度 8.9k', '官方看板娘'],
    ],
    actions: [
      { id: 'waving', label: '挥手问候', description: '开机或点击时欢快打招呼' },
      { id: 'concert-hum', label: '合奏哼唱', description: '拿起乐器为你演奏工作背景音' },
      { id: 'shy-cheek-peek', label: '害羞捂脸', description: '轻轻点一下脸颊触发的害羞反应' },
      { id: 'edge-crawl-bottom', label: '边缘漫步', description: '趴在任务栏上方好奇四处张望' },
      { id: 'feather-tickle', label: '羽毛逗弄', description: '用羽毛道具逗逗她的小肚皮' },
    ],
  },
  {
    id: 'nuonuo',
    name: '糯糯 Dora',
    enName: 'Dora / Nuonuo',
    folderName: 'NuonuoPet',
    code: '0021',
    price: 0,
    salesCount: 6540,
    category: 'official',
    categoryLabel: '创研看板',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '核心原创',
    license: 'WindowPet 原生开源协议',
    tagline: '“软乎乎的、爱回应你的小治愈伙伴，累了就戳戳我休息一下吧。”',
    description: '糯糯（Dora）拥有极其柔和舒缓的动作节奏，特别适合放在屏幕角落做静音陪伴。无论是羽毛逗弄还是轻快跳跃，都给工作学习带来满满治愈感。',
    mood: '软萌 / 治愈 / 慢节奏',
    traits: ['高萌跳跃', '羽毛互动', '柔和反馈', '防打扰陪伴'],
    image: 'pets/dora.png',
    animatedWebp: 'pets/dora-animated.webp',
    redeemCode: 'WPX-2026-DORA',
    canvas: '192x208',
    actionCount: 14,
    stats: [
      ['14 种', '专属动作'],
      ['免费', '开箱可用'],
      ['热度 6.5k', '舒缓减压'],
    ],
    actions: [
      { id: 'waving', label: '轻轻挥手', description: '静悄悄挥手，不打扰正在工作的你' },
      { id: 'jumping', label: '欢快跳跃', description: '完成任务时给你蹦跳鼓励' },
      { id: 'feather-tickle', label: '羽毛挠痒', description: '被羽毛逗到时眯起眼睛笑' },
      { id: 'running', label: '小碎步快跑', description: '拖拽移动时的可爱碎步' },
    ],
  },
  {
    id: 'fox',
    name: '灵敏小狐狸',
    enName: 'Huhu Fox',
    folderName: 'HuhuPet',
    code: '0005',
    price: 0,
    salesCount: 5780,
    category: 'official',
    categoryLabel: '创研看板',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '核心原创',
    license: 'WindowPet 原生开源协议',
    tagline: '“聪明机敏的狐狸搭档，提醒、待办和交互反馈从不漏掉！”',
    description: '小狐狸机灵俏皮，耳朵反应极其灵敏，对桌面逗弄工具有着极其生动的命中动作反馈，是提醒、番茄钟与日程备忘的绝佳助手。',
    mood: '机灵 / 敏捷 / 互动强',
    traits: ['长尾摇摆', '道具命中反馈', '灵敏提醒', '双向互动'],
    image: 'pets/fox.png',
    animatedWebp: 'pets/fox-animated.webp',
    redeemCode: 'WPX-2026-FOX',
    canvas: '192x208',
    actionCount: 15,
    stats: [
      ['15 种', '动作状态'],
      ['免费', '开箱可用'],
      ['热度 5.7k', '效率提醒'],
    ],
    actions: [
      { id: 'waving', label: '翘尾致意', description: '毛茸茸的大尾巴随节奏轻轻晃动' },
      { id: 'whip-hit', label: '鞭子命中', description: '被逗弄工具命中后生动的惊慌翻滚' },
      { id: 'feather-tickle', label: '羽毛逗弄', description: '歪头被羽毛逗弄的灵敏动作' },
      { id: 'reward', label: '获得奖励', description: '完成番茄钟或待办时的开心动作' },
    ],
  },
  {
    id: 'logo-guinea-pig',
    name: '豚鼠小鼻嘎',
    enName: 'Logo Guinea Pig',
    folderName: 'LogoGuineaPigPet',
    code: '0001',
    price: 0,
    salesCount: 7120,
    category: 'official',
    categoryLabel: '创研看板',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '核心原创',
    license: 'WindowPet 原生开源协议',
    tagline: '“WindowPet 官方初代吉祥物！小小一颗鼻嘎，大大世界陪伴。”',
    description: 'WindowPet 品牌标志的诞生原型！圆滚滚的一颗小豚鼠，身手矫健，支持全屏四边任意爬行，还会伸懒腰和钻进被窝睡觉。',
    mood: '经典 / 敏捷 / 原生吉祥物',
    traits: ['四向爬行', '吉祥物问候', '伸懒腰', '深度睡眠'],
    image: 'pets/logo_guinea_pig.png',
    redeemCode: 'WPX-2026-LOGO',
    canvas: '192x208',
    actionCount: 21,
    stats: [
      ['21 种', '全域动作'],
      ['免费', '开箱可用'],
      ['热度 7.1k', '品牌初代'],
    ],
    actions: [
      { id: 'mascot-greeting', label: '吉祥物专属问候', description: '立正向主人致敬' },
      { id: 'wake-stretch', label: '伸个大懒腰', description: '后腿向后拉伸打个大哈欠' },
      { id: 'sleep', label: '入睡打鼾', description: '缩成一颗小毛球呼呼大睡' },
    ],
  },

  // ----------------- 真实家宠·毛孩子组 (@米诺画画中 & @糖炒栗子) -----------------
  {
    id: 'maicuijiao',
    name: '麦脆角 (摇头猫)',
    enName: 'Maicuijiao Cat (Head-Track)',
    folderName: 'XiaobaTurnPet',
    code: '0025',
    price: 6.9,
    salesCount: 3410,
    category: 'home',
    categoryLabel: '治愈毛孩子',
    authorId: 'chestnut',
    authorName: '糖炒栗子定制工坊',
    authorHandle: '@ChestnutStudio',
    workType: '特邀定制',
    license: '特邀独家授权协议',
    tagline: '“无论你的鼠标移到哪里，我都会转头注视着你~”',
    description: '【全网爆款视线跟随】采用 25 帧全视角动态捕捉算法，猫猫脑袋会随着鼠标在屏幕上的每一次滑动而逼真转头注视，神态鲜活逼真。',
    mood: '注视 / 追踪 / 真实毛孩子',
    traits: ['25帧平滑转头', '鼠标视线跟随', '眼神深度互动', '真实毛发'],
    image: 'pets/xiaoba_turn.png',
    redeemCode: 'WPX-2026-TRACK',
    canvas: '192x208',
    actionCount: 25,
    stats: [
      ['25 帧', '深度视线追踪'],
      ['￥6.9', '限时特惠'],
      ['已售 3.4k+', '高口碑之选'],
    ],
    actions: [
      { id: 'head_track', label: '鼠标视线跟随转头', description: '鼠标移动到屏幕任何角落，小猫的脸都会实时转动注视过去' },
    ],
  },
  {
    id: 'xiaochai',
    name: '小柴犬',
    enName: 'Xiaochai',
    folderName: 'XiaochaiPet',
    code: '0012',
    price: 4.9,
    salesCount: 2890,
    category: 'home',
    categoryLabel: '治愈毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠写生',
    license: '米诺画画中创作者许可协议',
    tagline: '“忠诚憨厚的小柴犬，趴在屏幕旁默默等待主人摸头。”',
    description: '金黄色圆滚滚的小柴犬，拥有最让人心软的治愈笑容。待机时会摇着卷卷的尾巴趴在任务栏上打盹，拖拽时吐着舌头四脚乱蹬。',
    mood: '忠诚 / 憨厚 / 粘人',
    traits: ['摇尾巴', '摸头眯眼', '吐舌打滚', '护主陪伴'],
    image: 'pets/xiaochai.png',
    redeemCode: 'WPX-2026-XCHAI',
    canvas: '192x208',
    actionCount: 14,
    stats: [
      ['14 种', '犬类动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 2.8k+', '极度温顺'],
    ],
    actions: [
      { id: 'waving', label: '摇尾示好', description: '小尾巴摇出残影的乖巧模样' },
      { id: 'jumping', label: '兴奋扑腾', description: '见到主人时开心地蹦起来' },
      { id: 'waiting', label: '乖乖坐好', description: '蹲在屏幕边上两眼专注看着你' },
    ],
  },
  {
    id: 'bear',
    name: '抱抱小熊',
    enName: 'Bear',
    folderName: 'BearPet',
    code: '0015',
    price: 4.9,
    salesCount: 1820,
    category: 'home',
    categoryLabel: '治愈毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠写生',
    license: '米诺画画中创作者许可协议',
    tagline: '“毛茸茸的棕色小熊，想在你加班疲倦时给你一个暖暖的抱抱。”',
    description: '纯天然温暖系的小棕熊，圆耳朵短胳膊，走路憨态可掬。动作平缓可爱，适合喜欢泰迪熊玩偶风格的桌面伙伴。',
    mood: '温暖 / 憨态 / 踏实',
    traits: ['毛茸茸', '暖心拥抱', '慢吞吞', '睡眠陪伴'],
    image: 'pets/bear.png',
    redeemCode: 'WPX-2026-BEAR',
    canvas: '192x208',
    actionCount: 11,
    stats: [
      ['11 种', '自然动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 1.8k+', '毛绒质感'],
    ],
    actions: [
      { id: 'waving', label: '挥挥熊掌', description: '抬起厚厚的肉垫熊掌打招呼' },
      { id: 'drag', label: '悬空抱团', description: '被鼠标抓起时蜷成一个毛绒球' },
      { id: 'waiting', label: '发呆小憩', description: '坐在屏幕底部慢慢打哈欠' },
    ],
  },
  {
    id: 'bubu',
    name: '布布鼠',
    enName: 'Bubu',
    folderName: 'BubuPet',
    code: '0016',
    price: 4.9,
    salesCount: 2310,
    category: 'home',
    categoryLabel: '治愈毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠写生',
    license: '米诺画画中创作者许可协议',
    tagline: '“嘴里塞满了瓜子，嚼嚼嚼，鼓鼓的腮帮子藏着所有开心。”',
    description: '仓鼠系萌宠布布！脸颊总是塞得鼓鼓囊囊，两只前爪快速啃瓜子的动作百看不厌，在屏幕边缘跑来跑去特别灵动。',
    mood: '吃货 / 灵巧 / 仓鼠萌',
    traits: ['塞满腮帮', '快速啃咬', '圆滚滚', '翻滚跑动'],
    image: 'pets/bubu.png',
    redeemCode: 'WPX-2026-BUBU',
    canvas: '192x208',
    actionCount: 13,
    stats: [
      ['13 种', '吃货动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 2.3k+', '呆萌啃咬'],
    ],
    actions: [
      { id: 'waiting', label: '狂啃瓜子', description: '小爪捧着瓜子飞快咀嚼' },
      { id: 'waving', label: '探头招爪', description: '警惕地竖起耳朵打招呼' },
    ],
  },
  {
    id: 'mianmian',
    name: '绵绵羊',
    enName: 'Mianmian',
    folderName: 'MianmianPet',
    code: '0011',
    price: 4.9,
    salesCount: 1680,
    category: 'home',
    categoryLabel: '治愈毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠写生',
    license: '米诺画画中创作者许可协议',
    tagline: '“像一朵软绵绵的白云掉在桌面上，睡不着的时候就来数数我吧。”',
    description: '纯白云朵般蓬松的绵绵羊，有着棉花糖般的手感和慢悠悠的动作。工作学习时有它在身边，连焦虑的情绪都会变得温和宁静。',
    mood: '轻柔 / 恬静 / 助眠',
    traits: ['棉花糖手感', '轻柔踏步', '助眠光环', '安静陪伴'],
    image: 'pets/mianmian.png',
    redeemCode: 'WPX-2026-MIAN',
    canvas: '192x208',
    actionCount: 16,
    stats: [
      ['16 种', '绵柔动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 1.6k+', '恬淡舒缓'],
    ],
    actions: [
      { id: 'waiting', label: '悠闲嚼草', description: '轻柔咀嚼，眼神温顺安详' },
      { id: 'jumping', label: '小跳一下', description: '像云朵一样轻轻弹起落下' },
    ],
  },

  // ----------------- 动漫萌伴组 (@星野光年漫研所) -----------------
  {
    id: 'xiaoba',
    name: '小八猫',
    enName: 'Xiaoba',
    folderName: 'XiaobaPet',
    code: '0008',
    price: 6.9,
    salesCount: 4120,
    category: 'anime',
    categoryLabel: '动漫萌伴',
    authorId: 'hoshino',
    authorName: '星野光年漫研所',
    authorHandle: '@HoshinoAnime',
    workType: '动漫插画',
    license: '星野漫研所原创艺术许可',
    tagline: '“拿着吉他的小八猫，在你需要鼓励时弹出一首欢快的小曲~”',
    description: '小八拥有标志性的八字刘海与吉他合奏动作。温和勇敢的音乐搭档，在你需要鼓励时弹出一首欢快的小曲，为桌面注入清爽元气。',
    mood: '温和 / 勇敢 / 音乐家',
    traits: ['吉他演奏', '合奏连携', '呆萌表情', '暖心陪伴'],
    image: 'pets/xiaoba.png',
    redeemCode: 'WPX-2026-XBA',
    canvas: '192x208',
    actionCount: 20,
    stats: [
      ['20 种', '专属动画'],
      ['￥6.9', '超值特惠'],
      ['已售 4.1k+', '元气弹唱'],
    ],
    actions: [
      { id: 'sunny-guitar-bounce', label: '吉他弹唱', description: '抱着小吉他欢快跳动弹唱' },
      { id: 'concert-piano', label: '合奏协奏', description: '加入乐队大合唱的主旋律' },
      { id: 'waving', label: '双手招手', description: '两只猫爪一起挥动打招呼' },
    ],
  },
  {
    id: 'usagi',
    name: '乌萨奇兔兔',
    enName: 'Usagi',
    folderName: 'UsagiPet',
    code: '0007',
    price: 6.9,
    salesCount: 4890,
    category: 'anime',
    categoryLabel: '动漫萌伴',
    authorId: 'hoshino',
    authorName: '星野光年漫研所',
    authorHandle: '@HoshinoAnime',
    workType: '动漫插画',
    license: '星野漫研所原创艺术许可',
    tagline: '“乌啦啦啦！能量爆棚的元气小兔子，赶走所有班味与焦虑！”',
    description: '能量爆棚的元气小兔子，左右横跳和狂欢烟花舞步，充满魔性节奏感，为你扫除所有工作疲惫与班味！',
    mood: '高能 / 狂欢 / 搞笑魔性',
    traits: ['烟花合奏', '左右横跳', '狂欢舞步', '解压神宠'],
    image: 'pets/usagi.png',
    redeemCode: 'WPX-2026-USAGI',
    canvas: '192x208',
    actionCount: 22,
    stats: [
      ['22 种', '高能动作'],
      ['￥6.9', '超值特惠'],
      ['已售 4.8k+', '扫除班味'],
    ],
    actions: [
      { id: 'concert-fireworks', label: '烟花派对', description: '举起烟花棒在桌面狂热挥舞' },
      { id: 'side-step-bounce-tight', label: '左右横跳', description: '魔性节奏左右小跳步' },
      { id: 'waving', label: '大风车挥手', description: '手臂转成旋风式的大招呼' },
    ],
  },
  {
    id: 'nezuko',
    name: '祢豆子',
    enName: 'Nezuko',
    folderName: 'NezukoPet',
    code: '0026',
    price: 9.9,
    salesCount: 3670,
    category: 'anime',
    categoryLabel: '动漫萌伴',
    authorId: 'hoshino',
    authorName: '星野光年漫研所',
    authorHandle: '@HoshinoAnime',
    workType: '动漫插画',
    license: '星野漫研所原创艺术许可',
    tagline: '“粉红和服的小妹妹，在桌面上静静守护你。”',
    description: '粉红和服配竹筒造型的小女孩，动作轻盈柔和，在桌面上静静守护陪伴，治愈满分。',
    mood: '温柔 / 守护 / 经典名作',
    traits: ['和服竹筒', '缩小藏身', '守护光环', '经典还原'],
    image: 'pets/nezuko.png',
    redeemCode: 'WPX-2026-NEZU',
    canvas: '192x208',
    actionCount: 6,
    stats: [
      ['6 种', '专属动作'],
      ['￥9.9', '精品典藏'],
      ['已售 3.6k+', '静音守护'],
    ],
    actions: [
      { id: 'idle', label: '静静注视', description: '咬着竹筒眼睛眨巴眨巴看着你' },
    ],
  },
  {
    id: 'kukukaka',
    name: '库库咔咔 / 久美子',
    enName: 'Kumiko',
    folderName: 'KumikoPet',
    code: '0020',
    price: 6.9,
    salesCount: 2540,
    category: 'anime',
    categoryLabel: '动漫萌伴',
    authorId: 'hoshino',
    authorName: '星野光年漫研所',
    authorHandle: '@HoshinoAnime',
    workType: '动漫插画',
    license: '星野漫研所原创艺术许可',
    tagline: '“清爽灵动的日常主角，见证每一次成长与突破。”',
    description: '干净利落的画风与节奏，动作反馈清晰干脆。清新的学生制服装扮，带给你最纯粹的校园元气。',
    mood: '清爽 / 灵动 / 敏锐',
    traits: ['清爽动作', '跳跃干脆', '经典基线', '极佳兼容'],
    image: 'pets/kukukaka.png',
    animatedWebp: 'pets/kukukaka-animated.webp',
    redeemCode: 'WPX-2026-KUMI',
    canvas: '192x208',
    actionCount: 12,
    stats: [
      ['12 种', '精选动作'],
      ['￥6.9', '特惠解锁'],
      ['已售 2.5k+', '清爽利落'],
    ],
    actions: [
      { id: 'waving', label: '明亮挥手', description: '干净清爽的招手问候' },
      { id: 'jumping', label: '轻巧跃起', description: '敏捷灵巧的空中跳步' },
    ],
  },

  // ----------------- 森林与生灵组 (@自然漫步客) -----------------
  {
    id: 'lulu',
    name: '卡皮巴拉 水豚',
    enName: 'Lulu Capybara',
    folderName: 'LuluCapybaraPet',
    code: '0010',
    price: 4.9,
    salesCount: 5210,
    category: 'nature',
    categoryLabel: '森林与生灵',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然生灵',
    license: '自然漫步客手绘协议',
    tagline: '“精神状态极其稳定。天塌下来，我卡皮巴拉也只是闭目养神。”',
    description: '当代打工人最需要的精神图腾！头顶着小橘子的水豚卡皮巴拉，拥有全宇宙最稳定的情绪内核。无论外界如何纷乱，它依然气定神闲，是你的“情绪降温器”。',
    mood: '佛系 / 情绪稳定 / 慢调',
    traits: ['头顶橘子', '佛系入定', '缓慢咀嚼', '解压减负'],
    image: 'pets/lulu_capybara.png',
    redeemCode: 'WPX-2026-CAPY',
    canvas: '192x208',
    actionCount: 13,
    stats: [
      ['13 种', '佛系动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 5.2k+', '情绪降温'],
    ],
    actions: [
      { id: 'waiting', label: '闭目入定', description: '头顶橘子，微闭双眼感受生活' },
      { id: 'waving', label: '慢速招爪', description: '用0.5倍速缓缓抬手打招呼' },
      { id: 'feather-tickle', label: '泰然处之', description: '被羽毛撩拨也面不改色' },
    ],
  },
  {
    id: 'panda',
    name: '功夫大熊猫',
    enName: 'Panda',
    folderName: 'PandaPet',
    code: '0014',
    price: 4.9,
    salesCount: 3120,
    category: 'nature',
    categoryLabel: '森林与生灵',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然生灵',
    license: '自然漫步客手绘协议',
    tagline: '“黑眼圈是国宝的勋章，抱着大竹子，今天也是悠闲的一天！”',
    description: '憨态可掬的中国国宝大熊猫，动作慢条斯理，啃竹子的声音仿佛就在耳边。圆滚滚的黑白身体拖拽起来沉甸甸的，手感绝佳。',
    mood: '国宝 / 憨厚 / 闲适',
    traits: ['抱竹子', '就地翻滚', '黑眼圈同款', '慢节奏'],
    image: 'pets/panda.png',
    redeemCode: 'WPX-2026-PANDA',
    canvas: '192x208',
    actionCount: 14,
    stats: [
      ['14 种', '国宝动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 3.1k+', '沉稳国宝'],
    ],
    actions: [
      { id: 'waiting', label: '美滋滋啃竹子', description: '双手握着嫩竹叶吃得津津有味' },
      { id: 'waving', label: '挥手示意', description: '抬起大黑爪向你热情挥动' },
    ],
  },
  {
    id: 'penguin-sister',
    name: '企鹅妹妹',
    enName: 'Penguin Sister',
    folderName: 'PenguinSisterPet',
    code: '0013',
    price: 4.9,
    salesCount: 2190,
    category: 'nature',
    categoryLabel: '森林与生灵',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然生灵',
    license: '自然漫步客手绘协议',
    tagline: '“穿着小粉裙的南极小企鹅，摇摇晃晃走过你的屏幕。”',
    description: '头戴粉色蝴蝶结的乖巧小企鹅，走起路来左右摇摆，像一颗不倒翁。支持沿桌面下边沿滑冰式移动，呆萌度拉满。',
    mood: '乖巧 / 摇摆 / 冰雪系',
    traits: ['企鹅摇摆', '滑冰步', '蝴蝶结', '清凉陪伴'],
    image: 'pets/penguin_sister.png',
    redeemCode: 'WPX-2026-PENG',
    canvas: '192x208',
    actionCount: 15,
    stats: [
      ['15 种', '冰雪动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 2.1k+', '极地清凉'],
    ],
    actions: [
      { id: 'waving', label: '小翅膀扑腾', description: '短小的黑白翅膀飞快挥摆' },
      { id: 'jumping', label: '踮脚小跳', description: '开心地原地小跺脚' },
    ],
  },
  {
    id: 'huhu2',
    name: '赤狐烈焰',
    enName: 'Red Fox Huhu2',
    folderName: 'Huhu2Pet',
    code: '0024',
    price: 4.9,
    salesCount: 1980,
    category: 'nature',
    categoryLabel: '森林与生灵',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然生灵',
    license: '自然漫步客手绘协议',
    tagline: '“野生赤狐的烈焰进阶版！更热烈的毛色，更调皮的眼神。”',
    description: '野生赤狐的异色手绘款，拥有鲜红亮丽的皮毛与双倍好奇心。在屏幕上穿梭时格外抢眼，适合喜欢高饱和度活泼视觉的用户。',
    mood: '热情 / 调皮 / 异色款',
    traits: ['异色赤红', '机警立耳', '欢快奔跑', '亮眼吸睛'],
    image: 'pets/huhu2.png',
    redeemCode: 'WPX-2026-RED',
    canvas: '192x208',
    actionCount: 15,
    stats: [
      ['15 种', '动作模组'],
      ['￥4.9', '特惠解锁'],
      ['已售 1.9k+', '亮丽夺目'],
    ],
    actions: [
      { id: 'waving', label: '赤尾摇晃', description: '火红的大尾巴在屏幕边晃动' },
      { id: 'running', label: '飞速穿梭', description: '化作一团红火在桌面飞奔' },
    ],
  },

  // ----------------- 趣味整活组 (@整活大队 MemeLab) -----------------
  {
    id: 'salary-cat',
    name: '打工猫',
    enName: 'Salary Cat',
    folderName: 'SalaryCatPet',
    code: '0019',
    price: 3.9,
    salesCount: 4620,
    category: 'fun',
    categoryLabel: '趣味整活',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味动态',
    license: 'MemeLab 趣味共享协议',
    tagline: '“打工人的怨种猫猫分身：我起得比鸡早，工资拿得比谁都少！”',
    description: '眼神空洞、身穿小领带但毫无灵魂的打工猫。在你敲代码或做PPT时，它也在旁边机械敲键盘，是同病相怜的最佳摸鱼盟友。',
    mood: '怨种 / 摸鱼 / 打工魂',
    traits: ['敲键盘', '叹气连连', '摸鱼指南', '共情共鸣'],
    image: 'pets/salary_cat.png',
    redeemCode: 'WPX-2026-WORK',
    canvas: '192x208',
    actionCount: 8,
    stats: [
      ['8 种', '上班动作'],
      ['￥3.9', '摸鱼特惠'],
      ['已售 4.6k+', '打工怨种'],
    ],
    actions: [
      { id: 'hover', label: '疯狂敲键盘', description: '假装正在认真疯狂输出' },
      { id: 'click', label: '叹一口长气', description: '转头无奈叹气' },
    ],
  },
  {
    id: 'buya',
    name: '不鸭',
    enName: 'Buya Duck',
    folderName: 'BuyaPet',
    code: '0017',
    price: 3.9,
    salesCount: 3840,
    category: 'fun',
    categoryLabel: '趣味整活',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味动态',
    license: 'MemeLab 趣味共享协议',
    tagline: '“不要嘛~ 不要加班、不要内卷，今天也要做一个快乐的废物小鸭！”',
    description: '白白胖胖的呆萌小鸭子，标志性的大黄嘴和摆烂哲学，日常口头禅是“不鸭不鸭”。被鼠标点到时会扑棱小黄翅膀抗议，充满反差萌。',
    mood: '摆烂 / 反内卷 / 搞笑萌',
    traits: ['扑棱翅膀', '摇摆屁股', '拒绝加班', '魔性摇头'],
    image: 'pets/buya.png',
    redeemCode: 'WPX-2026-BUYA',
    canvas: '192x208',
    actionCount: 12,
    stats: [
      ['12 种', '抗议动作'],
      ['￥3.9', '摸鱼特惠'],
      ['已售 3.8k+', '拒绝内卷'],
    ],
    actions: [
      { id: 'waving', label: '拍拍小翅膀', description: '小黄翅膀扑棱扑棱拍打' },
      { id: 'failed', label: '瘫倒在地', description: '累了直接原地躺平摆烂' },
    ],
  },
  {
    id: 'kun-like',
    name: '小中分 / 篮球偶像',
    enName: 'Kun Like',
    folderName: 'KunLikePet',
    code: '0022',
    price: 4.9,
    salesCount: 4150,
    category: 'fun',
    categoryLabel: '趣味整活',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味动态',
    license: 'MemeLab 趣味共享协议',
    tagline: '“全民制作人大家好！背带裤一穿，整片桌面都是我的舞台！”',
    description: '灰色中分发型搭配经典背带裤，动作充满魔性律动与舞台喜感。只要他在桌面上，任何严肃的工作氛围都会秒变欢乐蹦迪现场！',
    mood: '魔性 / 舞台风 / 梗图狂喜',
    traits: ['魔性运球', '经典中分', '背带裤', '舞台走秀'],
    image: 'pets/kun_like.png',
    redeemCode: 'WPX-2026-KUN',
    canvas: '192x208',
    actionCount: 9,
    stats: [
      ['9 种', '舞台动作'],
      ['￥4.9', '特惠解锁'],
      ['已售 4.1k+', '魔性运球'],
    ],
    actions: [
      { id: 'idle', label: '偶像台风', description: '自信扶住刘海摆出标志性动作' },
      { id: 'click', label: '原地运球', description: '配合节奏展现华丽球技' },
    ],
  },
  {
    id: 'popo',
    name: '啵啵 Popo',
    enName: 'Popo',
    folderName: 'PopoPet',
    code: '0023',
    price: 4.9,
    salesCount: 3290,
    category: 'fun',
    categoryLabel: '趣味整活',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味动态',
    license: 'MemeLab 趣味共享协议',
    tagline: '“扭臀摇摆、欢乐蹦迪！让你的桌面瞬间变成动感夜店！”',
    description: '极具动感表现力的潮流小怪兽，拥有独特的骨骼手势舞与倒退警告动作。每一次点击都会触发惊喜的魔性跳舞动画。',
    mood: '潮流 / 动感 / 搞怪舞者',
    traits: ['手势舞', '倒退警告', '开心跳舞', '高能大动作'],
    image: 'pets/popo.png',
    redeemCode: 'WPX-2026-POPO',
    canvas: '192x208',
    actionCount: 10,
    stats: [
      ['10 种', '专属舞步'],
      ['￥4.9', '特惠解锁'],
      ['已售 3.2k+', '舞王降临'],
    ],
    actions: [
      { id: 'happy-dance', label: '开心蹦迪', description: '全身随节拍大开大合快乐摇摆' },
      { id: 'gesture-dance', label: '手势舞', description: '手指翻飞的潮流节奏手势' },
      { id: 'reverse-warning', label: '倒退警报', description: '搞笑倒退小碎步并挥舞双手' },
    ],
  },
]
