export interface PetAction {
  id: string
  label: string
  description: string
  preview?: string
}

export interface PetAuthor {
  id: string
  name: string
  handle: string
  role: string
  bio: string
  badge: string
  badgeColor: string
}

export const galleryAuthors: Record<string, PetAuthor> = {
  official: {
    id: 'official',
    name: 'WindowPet 创研所',
    handle: '@WindowPet_Dev',
    role: '官方原创研发组',
    bio: 'WindowPet 基础引擎与看板娘设计组，致力于原生高帧率交互与极轻量陪伴。',
    badge: '官方原创',
    badgeColor: '#2563eb',
  },
  mino: {
    id: 'mino',
    name: '米诺画画中',
    handle: '@MinoPixel',
    role: '独立家宠像素画师',
    bio: '专注真实猫狗生活照二创，首创 25 帧深度视线转头跟随系列，重度铲屎官。',
    badge: '家宠插画师',
    badgeColor: '#059669',
  },
  hoshino: {
    id: 'hoshino',
    name: '星野ACG同人漫研社',
    handle: '@HoshinoFanart',
    role: '民间二次元同人社团',
    bio: '民间动漫二创爱好者小组，致敬经典二次元形象，作品遵循个人非商用学习交流协议。',
    badge: '社区同人二创',
    badgeColor: '#7c3aed',
  },
  wildspirit: {
    id: 'wildspirit',
    name: '自然漫步客',
    handle: '@WildSpirit',
    role: '自然萌物绘者',
    bio: '热衷于自然界治愈野生动物手绘，代表作水豚卡皮巴拉与国宝大熊猫。',
    badge: '自然手绘',
    badgeColor: '#0891b2',
  },
  memelab: {
    id: 'memelab',
    name: '整活大队 MemeLab',
    handle: '@MemeLab_UP',
    role: '梗图搞怪研究室',
    bio: '打工人与互联网梗图二创爱好者，致力于给严肃的办公电脑桌面带来无厘头欢乐。',
    badge: '社区整活MOD',
    badgeColor: '#ea580c',
  },
  chestnut: {
    id: 'chestnut',
    name: '糖炒栗子定制工坊',
    handle: '@ChestnutStudio',
    role: '特邀家宠定制团队',
    bio: '专职为社区玩家定制自家毛孩子桌面伙伴，提供生活照建模与 1 对 1 动作还原。',
    badge: '特邀定制画师',
    badgeColor: '#db2777',
  },
}

export interface GalleryPet {
  id: string
  name: string
  enName: string
  folderName: string
  code: string
  category: 'official' | 'home' | 'anime' | 'nature' | 'fun'
  categoryLabel: string
  authorId: 'official' | 'mino' | 'hoshino' | 'wildspirit' | 'memelab' | 'chestnut'
  authorName: string
  authorHandle: string
  workType: '官方原生' | '家宠实拍' | '同人二创' | '自然萌物' | '趣味整活'
  license: string
  tagline: string
  description: string
  mood: string
  traits: string[]
  image: string
  animatedWebp?: string
  redeemCode: string
  canvas: string
  actionCount: number
  actions: PetAction[]
  stats: [string, string][]
  downloadUrl?: string
}

export const galleryCategories = [
  { id: 'all', label: '全部小鼻嘎', count: 21, icon: 'paw-print' },
  { id: 'official', label: '官方原创', count: 4, icon: 'sparkles' },
  { id: 'home', label: '真实家宠·毛孩子', count: 5, icon: 'home' },
  { id: 'anime', label: '同人二创·动漫社', count: 4, icon: 'heart' },
  { id: 'nature', label: '自然野趣·治愈界', count: 4, icon: 'paw-print' },
  { id: 'fun', label: '搞笑整活·梗图室', count: 4, icon: 'smile' },
] as const

export const galleryPets: GalleryPet[] = [
  // ----------------- 官方原创组 (@WindowPet 创研所) -----------------
  {
    id: 'jiyi',
    name: '吉伊',
    enName: 'Jiyi',
    folderName: 'JiyiPet',
    code: '0006',
    category: 'official',
    categoryLabel: '官方原创',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '官方原生',
    license: 'WindowPet 原生开源协议',
    tagline: '“今天也是元气满满的一天！打开电脑先挥挥手打个招呼吧~”',
    description: '吉伊是 WindowPet 的核心原创看板伙伴，拥有全场最丰富的动作生态。她会用害羞、跳跃、小鞠躬和合奏哼唱回应你的每一次点击与拖拽，在桌面边沿还会偷偷探头！',
    mood: '活泼 / 亲近 / 萌系元气',
    traits: ['合奏哼唱', '边缘爬行', '超多害羞动作', '全场景互动'],
    image: 'pets/jiyi.png',
    animatedWebp: 'pets/jiyi-animated.webp',
    redeemCode: 'WPX-2026-JIYI',
    canvas: '192x208',
    actionCount: 29,
    stats: [
      ['29 种', '动作生态'],
      ['官方原创', '核心看板娘'],
      ['免登录', '永久可用'],
    ],
    actions: [
      { id: 'waving', label: '挥手问候', description: '开机或点击时欢快打招呼' },
      { id: 'concert-hum', label: '合奏哼唱', description: '拿起乐器为你演奏工作背景音' },
      { id: 'shy-cheek-peek', label: '害羞捂脸', description: '轻轻点一下脸颊触发的害羞反应' },
      { id: 'edge-crawl-bottom', label: '边缘漫步', description: '趴在任务栏上方好奇四处张望' },
      { id: 'feather-tickle', label: '羽毛逗弄', description: '用羽毛道具逗逗她的小肚皮' },
    ],
  },
  {
    id: 'nuonuo',
    name: '糯糯 Dora',
    enName: 'Dora / Nuonuo',
    folderName: 'NuonuoPet',
    code: '0021',
    category: 'official',
    categoryLabel: '官方原创',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '官方原生',
    license: 'WindowPet 原生开源协议',
    tagline: '“软乎乎的、爱回应你的小治愈伙伴，累了就戳戳我休息一下吧。”',
    description: '糯糯（Dora）拥有极其柔和舒缓的动作节奏，特别适合放在屏幕角落做静音陪伴。无论是羽毛逗弄还是轻快跳跃，都给工作学习带来满满治愈感。',
    mood: '软萌 / 治愈 / 慢节奏',
    traits: ['高萌跳跃', '羽毛互动', '柔和反馈', '防打扰陪伴'],
    image: 'pets/dora.png',
    animatedWebp: 'pets/dora-animated.webp',
    redeemCode: 'WPX-2026-DORA',
    canvas: '192x208',
    actionCount: 14,
    stats: [
      ['14 种', '专属动作'],
      ['官方原创', '静音慢调陪伴'],
      ['零干扰', '舒缓减压'],
    ],
    actions: [
      { id: 'waving', label: '轻轻挥手', description: '静悄悄挥手，不打扰正在工作的你' },
      { id: 'jumping', label: '欢快跳跃', description: '完成任务时给你蹦跳鼓励' },
      { id: 'feather-tickle', label: '羽毛挠痒', description: '被羽毛逗到时眯起眼睛笑' },
      { id: 'running', label: '小碎步快跑', description: '拖拽移动时的可爱碎步' },
    ],
  },
  {
    id: 'fox',
    name: '灵敏小狐狸',
    enName: 'Huhu Fox',
    folderName: 'HuhuPet',
    code: '0005',
    category: 'official',
    categoryLabel: '官方原创',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '官方原生',
    license: 'WindowPet 原生开源协议',
    tagline: '“聪明机敏的狐狸搭档，提醒、待办和交互反馈从不漏掉！”',
    description: '小狐狸机灵俏皮，耳朵反应极其灵敏，对桌面逗弄工具有着极其生动的命中动作反馈，是提醒、番茄钟与日程备忘的绝佳助手。',
    mood: '机灵 / 敏捷 / 互动强',
    traits: ['长尾摇摆', '道具命中反馈', '灵敏提醒', '双向互动'],
    image: 'pets/fox.png',
    animatedWebp: 'pets/fox-animated.webp',
    redeemCode: 'WPX-2026-FOX',
    canvas: '192x208',
    actionCount: 15,
    stats: [
      ['15 种', '动作状态'],
      ['官方原创', '效率提醒助手'],
      ['强反馈', '动作鲜活'],
    ],
    actions: [
      { id: 'waving', label: '翘尾致意', description: '毛茸茸的大尾巴随节奏轻轻晃动' },
      { id: 'whip-hit', label: '鞭子命中', description: '被逗弄工具命中后生动的惊慌翻滚' },
      { id: 'feather-tickle', label: '羽毛逗弄', description: '歪头被羽毛逗弄的灵敏动作' },
      { id: 'reward', label: '获得奖励', description: '完成番茄钟或待办时的开心动作' },
    ],
  },
  {
    id: 'logo-guinea-pig',
    name: '豚鼠小鼻嘎',
    enName: 'Logo Guinea Pig',
    folderName: 'LogoGuineaPigPet',
    code: '0001',
    category: 'official',
    categoryLabel: '官方原创',
    authorId: 'official',
    authorName: 'WindowPet 创研所',
    authorHandle: '@WindowPet_Dev',
    workType: '官方原生',
    license: 'WindowPet 原生开源协议',
    tagline: '“WindowPet 官方初代吉祥物！小小一颗鼻嘎，大大世界陪伴。”',
    description: 'WindowPet 品牌标志的诞生原型！圆滚滚的一颗小豚鼠，身手矫健，支持全屏四边任意爬行，还会伸懒腰和钻进被窝睡觉。',
    mood: '经典 / 敏捷 / 原生吉祥物',
    traits: ['四向爬行', '吉祥物问候', '伸懒腰', '深度睡眠'],
    image: 'pets/logo_guinea_pig.png',
    redeemCode: 'WPX-2026-LOGO',
    canvas: '192x208',
    actionCount: 21,
    stats: [
      ['21 种', '全域动作'],
      ['官方创始', '品牌初代原型'],
      ['四向爬墙', '边框自由'],
    ],
    actions: [
      { id: 'mascot-greeting', label: '吉祥物专属问候', description: '立正向主人致敬' },
      { id: 'wake-stretch', label: '伸个大懒腰', description: '后腿向后拉伸打个大哈欠' },
      { id: 'sleep', label: '入睡打鼾', description: '缩成一颗小毛球呼呼大睡' },
    ],
  },

  // ----------------- 真实家宠·毛孩子组 (@米诺画画中) -----------------
  {
    id: 'maicuijiao',
    name: '家宠·麦脆角 (摇头猫)',
    enName: 'Maicuijiao Cat (Head-Track)',
    folderName: 'XiaobaTurnPet',
    code: '0025',
    category: 'home',
    categoryLabel: '真实家宠·毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠实拍',
    license: 'CC-BY-NC 4.0 (个人非商用)',
    tagline: '“真正的真实家宠！无论你的鼠标移到哪里，我都会转头注视着你~”',
    description: '【画师米诺真实家宠代表作】基于画师生活中的爱猫“麦脆角”实拍打造，采用 25 帧视线追踪算法。它的猫猫脸蛋会随着鼠标在屏幕上的每一次滑动而逼真转头注视，是全网唯一眼神跟随的实拍家宠！',
    mood: '注视 / 追踪 / 真实毛孩子',
    traits: ['真实家宠实拍', '25帧平滑转头', '鼠标视线跟随', '眼神深度互动'],
    image: 'pets/xiaoba_turn.png',
    redeemCode: 'WPX-2026-TRACK',
    canvas: '192x208',
    actionCount: 25,
    stats: [
      ['25 帧', '深度视线追踪'],
      ['生活实拍', '作者 @米诺'],
      ['时刻注视', '跟随光标转头'],
    ],
    actions: [
      { id: 'head_track', label: '鼠标视线跟随转头', description: '鼠标移动到屏幕任何角落，小猫的脸都会实时转动注视过去' },
    ],
  },
  {
    id: 'xiaochai',
    name: '小柴犬',
    enName: 'Xiaochai',
    folderName: 'XiaochaiPet',
    code: '0012',
    category: 'home',
    categoryLabel: '真实家宠·毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠实拍',
    license: 'CC-BY-NC 4.0 (个人非商用)',
    tagline: '“忠诚憨厚的小柴犬，趴在屏幕旁默默等待主人摸头。”',
    description: '金黄色圆滚滚的小柴犬，拥有最让人心软的治愈笑容。待机时会摇着卷卷的尾巴趴在任务栏上打盹，拖拽时吐着舌头四脚乱蹬，萌化所有爱狗人士。',
    mood: '忠诚 / 憨厚 / 粘人',
    traits: ['摇尾巴', '摸头眯眼', '吐舌打滚', '护主陪伴'],
    image: 'pets/xiaochai.png',
    redeemCode: 'WPX-2026-XCHAI',
    canvas: '192x208',
    actionCount: 14,
    stats: [
      ['14 种', '犬类动作'],
      ['家宠手绘', '作者 @米诺'],
      ['极度温顺', '随时摸头'],
    ],
    actions: [
      { id: 'waving', label: '摇尾示好', description: '小尾巴摇出残影的乖巧模样' },
      { id: 'jumping', label: '兴奋扑腾', description: '见到主人时开心地蹦起来' },
      { id: 'waiting', label: '乖乖坐好', description: '蹲在屏幕边上两眼专注看着你' },
    ],
  },
  {
    id: 'bear',
    name: '抱抱小熊',
    enName: 'Bear',
    folderName: 'BearPet',
    code: '0015',
    category: 'home',
    categoryLabel: '真实家宠·毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠实拍',
    license: 'CC-BY-NC 4.0 (个人非商用)',
    tagline: '“毛茸茸的棕色小熊，想在你加班疲倦时给你一个暖暖的抱抱。”',
    description: '纯天然温暖系的小棕熊，圆耳朵短胳膊，走路憨态可掬。动作平缓可爱，适合喜欢纯真泰迪熊玩偶风格的桌面伙伴。',
    mood: '温暖 / 憨态 / 踏实',
    traits: ['毛茸茸', '暖心拥抱', '慢吞吞', '睡眠陪伴'],
    image: 'pets/bear.png',
    redeemCode: 'WPX-2026-BEAR',
    canvas: '192x208',
    actionCount: 11,
    stats: [
      ['11 种', '自然动作'],
      ['毛绒手绘', '作者 @米诺'],
      ['轻量资源', '快速载入'],
    ],
    actions: [
      { id: 'waving', label: '挥挥熊掌', description: '抬起厚厚的肉垫熊掌打招呼' },
      { id: 'drag', label: '悬空抱团', description: '被鼠标抓起时蜷成一个毛绒球' },
      { id: 'waiting', label: '发呆小憩', description: '坐在屏幕底部慢慢打哈欠' },
    ],
  },
  {
    id: 'bubu',
    name: '布布鼠',
    enName: 'Bubu',
    folderName: 'BubuPet',
    code: '0016',
    category: 'home',
    categoryLabel: '真实家宠·毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠实拍',
    license: 'CC-BY-NC 4.0 (个人非商用)',
    tagline: '“嘴里塞满了瓜子，嚼嚼嚼，鼓鼓的腮帮子藏着所有开心。”',
    description: '仓鼠系萌宠布布！脸颊总是塞得鼓鼓囊囊，两只前爪快速啃瓜子的动作百看不厌，在屏幕边缘跑来跑去特别灵动，还原了居家仓鼠的生活习性。',
    mood: '吃货 / 灵巧 / 仓鼠萌',
    traits: ['塞满腮帮', '快速啃咬', '圆滚滚', '翻滚跑动'],
    image: 'pets/bubu.png',
    redeemCode: 'WPX-2026-BUBU',
    canvas: '192x208',
    actionCount: 13,
    stats: [
      ['13 种', '吃货动作'],
      ['家养仓鼠', '作者 @米诺'],
      ['解馋解压', '可爱啃咬'],
    ],
    actions: [
      { id: 'waiting', label: '狂啃瓜子', description: '小爪捧着瓜子飞快咀嚼' },
      { id: 'waving', label: '探头招爪', description: '警惕地竖起耳朵打招呼' },
    ],
  },
  {
    id: 'mianmian',
    name: '绵绵羊',
    enName: 'Mianmian',
    folderName: 'MianmianPet',
    code: '0011',
    category: 'home',
    categoryLabel: '真实家宠·毛孩子',
    authorId: 'mino',
    authorName: '米诺画画中',
    authorHandle: '@MinoPixel',
    workType: '家宠实拍',
    license: 'CC-BY-NC 4.0 (个人非商用)',
    tagline: '“像一朵软绵绵的白云掉在桌面上，睡不着的时候就来数数我吧。”',
    description: '纯白云朵般蓬松的绵绵羊，有着棉花糖般的手感和慢悠悠的动作。晚上工作时有它在身边，连焦虑的情绪都会变得温和宁静。',
    mood: '轻柔 / 恬静 / 助眠',
    traits: ['棉花糖手感', '轻柔踏步', '助眠光环', '安静陪伴'],
    image: 'pets/mianmian.png',
    redeemCode: 'WPX-2026-MIAN',
    canvas: '192x208',
    actionCount: 16,
    stats: [
      ['16 种', '绵柔动作'],
      ['轻柔手绘', '作者 @米诺'],
      ['助眠安抚', '不扰思绪'],
    ],
    actions: [
      { id: 'waiting', label: '悠闲嚼草', description: '轻柔咀嚼，眼神温顺安详' },
      { id: 'jumping', label: '小跳一下', description: '像云朵一样轻轻弹起落下' },
    ],
  },

  // ----------------- 同人二创·动漫社 (@星野ACG同人漫研社) -----------------
  {
    id: 'xiaoba',
    name: '小八猫',
    enName: 'Xiaoba',
    folderName: 'XiaobaPet',
    code: '0008',
    category: 'anime',
    categoryLabel: '同人二创·动漫社',
    authorId: 'hoshino',
    authorName: '星野ACG同人漫研社',
    authorHandle: '@HoshinoFanart',
    workType: '同人二创',
    license: '玩家同人二创 · 个人非商用交流',
    tagline: '“拿着吉他的小八猫，在你需要鼓励时弹出一首欢快的小曲~”',
    description: '【民间同人二创模组】由星野ACG同人漫研社爱好者制作上传。小八拥有标志性的八字刘海与吉他合奏动作。声明：本形象由玩家社区自发分享，仅供桌面美化技术交流，非官方版权角色。',
    mood: '温和 / 勇敢 / 音乐家',
    traits: ['吉他演奏', '合奏连携', '呆萌表情', '暖心陪伴'],
    image: 'pets/xiaoba.png',
    redeemCode: 'WPX-2026-XBA',
    canvas: '192x208',
    actionCount: 20,
    stats: [
      ['20 种', '同人动画'],
      ['民间二创', '作者 @星野ACG'],
      ['非商用', '玩家分享'],
    ],
    actions: [
      { id: 'sunny-guitar-bounce', label: '吉他弹唱', description: '抱着小吉他欢快跳动弹唱' },
      { id: 'concert-piano', label: '合奏协奏', description: '加入乐队大合唱的主旋律' },
      { id: 'waving', label: '双手招手', description: '两只猫爪一起挥动打招呼' },
    ],
  },
  {
    id: 'usagi',
    name: '乌萨奇兔兔',
    enName: 'Usagi',
    folderName: 'UsagiPet',
    code: '0007',
    category: 'anime',
    categoryLabel: '同人二创·动漫社',
    authorId: 'hoshino',
    authorName: '星野ACG同人漫研社',
    authorHandle: '@HoshinoFanart',
    workType: '同人二创',
    license: '玩家同人二创 · 个人非商用交流',
    tagline: '“乌啦啦啦！能量爆棚的疯癫小兔子，赶走所有班味与焦虑！”',
    description: '【民间同人二创模组】由星野漫研社成员自制分享。极度兴奋、永远元气满满的魔性小兔子。声明：本角色为社区玩家二创产物，仅供个人非商用把玩，请勿用于任何商业营利。',
    mood: '高能 / 狂欢 / 搞笑魔性',
    traits: ['烟花合奏', '左右横跳', '狂欢舞步', '解压神宠'],
    image: 'pets/usagi.png',
    redeemCode: 'WPX-2026-USAGI',
    canvas: '192x208',
    actionCount: 22,
    stats: [
      ['22 种', '高能动作'],
      ['民间同人', '作者 @星野ACG'],
      ['狂暴能量', '扫除疲惫'],
    ],
    actions: [
      { id: 'concert-fireworks', label: '烟花派对', description: '举起烟花棒在桌面狂热挥舞' },
      { id: 'side-step-bounce-tight', label: '左右横跳', description: '魔性节奏左右小跳步' },
      { id: 'waving', label: '大风车挥手', description: '手臂转成旋风式的大招呼' },
    ],
  },
  {
    id: 'nezuko',
    name: '祢豆子',
    enName: 'Nezuko',
    folderName: 'NezukoPet',
    code: '0026',
    category: 'anime',
    categoryLabel: '同人二创·动漫社',
    authorId: 'hoshino',
    authorName: '星野ACG同人漫研社',
    authorHandle: '@HoshinoFanart',
    workType: '同人二创',
    license: '玩家同人二创 · 个人非商用交流',
    tagline: '“咬着竹筒的小妹妹，在桌面箱子里静静守护你。”',
    description: '【民间二次元同人致敬模组】粉红和服配竹筒造型，由社区同人爱好者制作分享。声明：本模组由星野ACG漫研社提供，仅供二次元爱好者个人桌面美化交流，WindowPet 官方不享有角色版权。',
    mood: '温柔 / 守护 / 动漫名作',
    traits: ['和服竹筒', '缩小藏身', '守护光环', '经典还原'],
    image: 'pets/nezuko.png',
    redeemCode: 'WPX-2026-NEZU',
    canvas: '192x208',
    actionCount: 6,
    stats: [
      ['6 种', '专属动作'],
      ['民间同人', '作者 @星野ACG'],
      ['致敬经典', '静音陪伴'],
    ],
    actions: [
      { id: 'idle', label: '静静注视', description: '咬着竹筒眼睛眨巴眨巴看着你' },
    ],
  },
  {
    id: 'kukukaka',
    name: '库库咔咔 / 久美子',
    enName: 'Kumiko',
    folderName: 'KumikoPet',
    code: '0020',
    category: 'anime',
    categoryLabel: '同人二创·动漫社',
    authorId: 'hoshino',
    authorName: '星野ACG同人漫研社',
    authorHandle: '@HoshinoFanart',
    workType: '同人二创',
    license: '玩家同人二创 · 个人非商用交流',
    tagline: '“清爽灵动的日常主角，见证了每一次新特性的迭代诞生。”',
    description: '【吹奏乐同人致敬模组】干净利落的画风与节奏，动作反馈清晰干脆。声明：本形象由玩家社区同人漫研社制作分享，仅供个人非商用学习交流。',
    mood: '清爽 / 灵动 / 敏锐',
    traits: ['清爽动作', '跳跃干脆', '经典基线', '极佳兼容'],
    image: 'pets/kukukaka.png',
    animatedWebp: 'pets/kukukaka-animated.webp',
    redeemCode: 'WPX-2026-KUMI',
    canvas: '192x208',
    actionCount: 12,
    stats: [
      ['12 种', '精选动作'],
      ['同人分享', '作者 @星野ACG'],
      ['高响应率', '利落干脆'],
    ],
    actions: [
      { id: 'waving', label: '明亮挥手', description: '干净清爽的招手问候' },
      { id: 'jumping', label: '轻巧跃起', description: '敏捷灵巧的空中跳步' },
    ],
  },

  // ----------------- 自然野趣·治愈界 (@自然漫步客) -----------------
  {
    id: 'lulu',
    name: '卡皮巴拉 水豚',
    enName: 'Lulu Capybara',
    folderName: 'LuluCapybaraPet',
    code: '0010',
    category: 'nature',
    categoryLabel: '自然野趣·治愈界',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然萌物',
    license: '知识共享 CC-BY-NC 4.0',
    tagline: '“精神状态极其稳定。天塌下来，我卡皮巴拉也只是闭目养神。”',
    description: '当代打工人最需要的精神图腾！头顶着小橘子的水豚卡皮巴拉，拥有全宇宙最稳定的情绪内核。无论外界如何纷乱，它依然气定神闲，是你的“情绪降温器”。',
    mood: '佛系 / 情绪稳定 / 慢调',
    traits: ['头顶橘子', '佛系入定', '缓慢咀嚼', '解压减负'],
    image: 'pets/lulu_capybara.png',
    redeemCode: 'WPX-2026-CAPY',
    canvas: '192x208',
    actionCount: 13,
    stats: [
      ['13 种', '佛系动作'],
      ['自然手绘', '作者 @漫步客'],
      ['佛系入定', '降噪减压'],
    ],
    actions: [
      { id: 'waiting', label: '闭目入定', description: '头顶橘子，微闭双眼感受生活' },
      { id: 'waving', label: '慢速招爪', description: '用0.5倍速缓缓抬手打招呼' },
      { id: 'feather-tickle', label: '泰然处之', description: '被羽毛撩拨也面不改色' },
    ],
  },
  {
    id: 'panda',
    name: '功夫大熊猫',
    enName: 'Panda',
    folderName: 'PandaPet',
    code: '0014',
    category: 'nature',
    categoryLabel: '自然野趣·治愈界',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然萌物',
    license: '知识共享 CC-BY-NC 4.0',
    tagline: '“黑眼圈是国宝的勋章，抱着大竹子，今天也是悠闲的一天！”',
    description: '憨态可掬的中国国宝大熊猫，动作慢条斯理，啃竹子的声音仿佛就在耳边。圆滚滚的黑白身体拖拽起来沉甸甸的，手感绝佳。',
    mood: '国宝 / 憨厚 / 闲适',
    traits: ['抱竹子', '就地翻滚', '黑眼圈同款', '慢节奏'],
    image: 'pets/panda.png',
    redeemCode: 'WPX-2026-PANDA',
    canvas: '192x208',
    actionCount: 14,
    stats: [
      ['14 种', '国宝动作'],
      ['自然手绘', '作者 @漫步客'],
      ['憨厚沉稳', '啃竹大王'],
    ],
    actions: [
      { id: 'waiting', label: '美滋滋啃竹子', description: '双手握着嫩竹叶吃得津津有味' },
      { id: 'waving', label: '挥手示意', description: '抬起大黑爪向你热情挥动' },
    ],
  },
  {
    id: 'penguin-sister',
    name: '企鹅妹妹',
    enName: 'Penguin Sister',
    folderName: 'PenguinSisterPet',
    code: '0013',
    category: 'nature',
    categoryLabel: '自然野趣·治愈界',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然萌物',
    license: '知识共享 CC-BY-NC 4.0',
    tagline: '“穿着小粉裙的南极小企鹅，摇摇晃晃走过你的屏幕。”',
    description: '头戴粉色蝴蝶结的乖巧小企鹅，走起路来左右摇摆，像一颗不倒翁。支持沿桌面下边沿滑冰式移动，呆萌度拉满。',
    mood: '乖巧 / 摇摆 / 冰雪系',
    traits: ['企鹅摇摆', '滑冰步', '蝴蝶结', '清凉陪伴'],
    image: 'pets/penguin_sister.png',
    redeemCode: 'WPX-2026-PENG',
    canvas: '192x208',
    actionCount: 15,
    stats: [
      ['15 种', '冰雪动作'],
      ['自然萌宠', '作者 @漫步客'],
      ['夏日降温', '极地清凉'],
    ],
    actions: [
      { id: 'waving', label: '小翅膀扑腾', description: '短小的黑白翅膀飞快挥摆' },
      { id: 'jumping', label: '踮脚小跳', description: '开心地原地小跺脚' },
    ],
  },
  {
    id: 'huhu2',
    name: '赤狐烈焰',
    enName: 'Red Fox Huhu2',
    folderName: 'Huhu2Pet',
    code: '0024',
    category: 'nature',
    categoryLabel: '自然野趣·治愈界',
    authorId: 'wildspirit',
    authorName: '自然漫步客',
    authorHandle: '@WildSpirit',
    workType: '自然萌物',
    license: '知识共享 CC-BY-NC 4.0',
    tagline: '“野生赤狐的烈焰进阶版！更热烈的毛色，更调皮的眼神。”',
    description: '野生赤狐的异色手绘款，拥有鲜红亮丽的皮毛与双倍好奇心。在屏幕上穿梭时格外抢眼，适合喜欢高饱和度活泼视觉的用户。',
    mood: '热情 / 调皮 / 异色款',
    traits: ['异色赤红', '机警立耳', '欢快奔跑', '亮眼吸睛'],
    image: 'pets/huhu2.png',
    redeemCode: 'WPX-2026-RED',
    canvas: '192x208',
    actionCount: 15,
    stats: [
      ['15 种', '动作模组'],
      ['异色野生', '作者 @漫步客'],
      ['高辨识度', '亮丽夺目'],
    ],
    actions: [
      { id: 'waving', label: '赤尾摇晃', description: '火红的大尾巴在屏幕边晃动' },
      { id: 'running', label: '飞速穿梭', description: '化作一团红火在桌面飞奔' },
    ],
  },

  // ----------------- 搞笑整活·梗图室 (@整活大队 MemeLab) -----------------
  {
    id: 'salary-cat',
    name: '打工猫',
    enName: 'Salary Cat',
    folderName: 'SalaryCatPet',
    code: '0019',
    category: 'fun',
    categoryLabel: '搞笑整活·梗图室',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味整活',
    license: '社区趣味共享协议',
    tagline: '“打工人的怨种猫猫分身：我起得比鸡早，工资拿得比谁都少！”',
    description: '眼神空洞、身穿小领带但毫无灵魂的打工猫。在你敲代码或做PPT时，它也在旁边机械敲键盘，是同病相怜的最佳摸鱼盟友。',
    mood: '怨种 / 摸鱼 / 打工魂',
    traits: ['敲键盘', '叹气连连', '摸鱼指南', '共情共鸣'],
    image: 'pets/salary_cat.png',
    redeemCode: 'WPX-2026-WORK',
    canvas: '192x208',
    actionCount: 8,
    stats: [
      ['8 种', '上班动作'],
      ['社区整活', '作者 @MemeLab'],
      ['怨种神韵', '极度真实'],
    ],
    actions: [
      { id: 'hover', label: '疯狂敲键盘', description: '假装正在认真疯狂输出' },
      { id: 'click', label: '叹一口长气', description: '转头无奈叹气' },
    ],
  },
  {
    id: 'buya',
    name: '不鸭',
    enName: 'Buya Duck',
    folderName: 'BuyaPet',
    code: '0017',
    category: 'fun',
    categoryLabel: '搞笑整活·梗图室',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味整活',
    license: '社区趣味共享协议',
    tagline: '“不要嘛~ 不要加班、不要内卷，今天也要做一个快乐的废物小鸭！”',
    description: '白白胖胖的呆萌小鸭子，标志性的大黄嘴和摆烂哲学，日常口头禅是“不鸭不鸭”。被鼠标点到时会扑棱小黄翅膀抗议，充满反差萌。',
    mood: '摆烂 / 反内卷 / 搞笑萌',
    traits: ['扑棱翅膀', '摇摆屁股', '拒绝加班', '魔性摇头'],
    image: 'pets/buya.png',
    redeemCode: 'WPX-2026-BUYA',
    canvas: '192x208',
    actionCount: 12,
    stats: [
      ['12 种', '抗议动作'],
      ['社区整活', '作者 @MemeLab'],
      ['摇晃呆萌', '开心果'],
    ],
    actions: [
      { id: 'waving', label: '拍拍小翅膀', description: '小黄翅膀扑棱扑棱拍打' },
      { id: 'failed', label: '瘫倒在地', description: '累了直接原地躺平摆烂' },
    ],
  },
  {
    id: 'kun-like',
    name: '小中分 / 篮球偶像',
    enName: 'Kun Like',
    folderName: 'KunLikePet',
    code: '0022',
    category: 'fun',
    categoryLabel: '搞笑整活·梗图室',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味整活',
    license: '社区趣味共享协议',
    tagline: '“全民制作人大家好！背带裤一穿，整片桌面都是我的舞台！”',
    description: '灰色中分发型搭配经典背带裤，动作充满魔性律动与舞台喜感。只要他在桌面上，任何严肃的工作氛围都会秒变欢乐蹦迪现场！',
    mood: '魔性 / 舞台风 / 梗图狂喜',
    traits: ['魔性运球', '经典中分', '背带裤', '舞台走秀'],
    image: 'pets/kun_like.png',
    redeemCode: 'WPX-2026-KUN',
    canvas: '192x208',
    actionCount: 9,
    stats: [
      ['9 种', '舞台动作'],
      ['社区整活', '作者 @MemeLab'],
      ['全屏活力', '快乐源泉'],
    ],
    actions: [
      { id: 'idle', label: '偶像台风', description: '自信扶住刘海摆出标志性动作' },
      { id: 'click', label: '原地运球', description: '配合节奏展现华丽球技' },
    ],
  },
  {
    id: 'popo',
    name: '啵啵 Popo',
    enName: 'Popo',
    folderName: 'PopoPet',
    code: '0023',
    category: 'fun',
    categoryLabel: '搞笑整活·梗图室',
    authorId: 'memelab',
    authorName: '整活大队 MemeLab',
    authorHandle: '@MemeLab_UP',
    workType: '趣味整活',
    license: '社区趣味共享协议',
    tagline: '“扭臀摇摆、欢乐蹦迪！让你的桌面瞬间变成动感夜店！”',
    description: '极具动感表现力的潮流小怪兽，拥有独特的骨骼手势舞与倒退警告动作。每一次点击都会触发惊喜的魔性跳舞动画。',
    mood: '潮流 / 动感 / 搞怪舞者',
    traits: ['手势舞', '倒退警告', '开心跳舞', '高能大动作'],
    image: 'pets/popo.png',
    redeemCode: 'WPX-2026-POPO',
    canvas: '192x208',
    actionCount: 10,
    stats: [
      ['10 种', '专属舞步'],
      ['社区整活', '作者 @MemeLab'],
      ['高能潮流', '舞王降临'],
    ],
    actions: [
      { id: 'happy-dance', label: '开心蹦迪', description: '全身随节拍大开大合快乐摇摆' },
      { id: 'gesture-dance', label: '手势舞', description: '手指翻飞的潮流节奏手势' },
      { id: 'reverse-warning', label: '倒退警报', description: '搞笑倒退小碎步并挥舞双手' },
    ],
  },
]
