from .constants import DEFAULT_ASSETS_DIR


ASSETS_DIR = DEFAULT_ASSETS_DIR
WINDOWS = []
CONTROL_PANEL = None
TRAY_ICON = None
EXITING = False
CONFIG_WARNINGS = []
RECENT_DIAGNOSTICS = []
INTERACTION_CONTROLLER = None
MEDAL_STORE = None
