; Script generated by Antigravity for WindowPet
; Inno Setup 6.x packaging script

#define MyAppName "WindowPet"
#define MyAppDisplayName "WindowPet 桌面宠物"
#define MyAppVersion "1.0.32"
#define MyAppPublisher "WindowPet Open Source Community"
#define MyAppURL "https://github.com/WindowPet/WindowPet"
#define MyAppExeName "Window Pet.exe"

[Setup]
; App basic identity
AppId={{8B264E48-692B-4BC2-94AE-B1D6539C0A74}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppDisplayName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

; Install directory & privilege
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppDisplayName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

; Output configuration
OutputDir=..\Output
OutputBaseFilename=WindowPet_Setup_v{#MyAppVersion}
SetupIconFile=..\icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

; Compression & Modern Visuals
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "chinesesimp"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce
Name: "startupicon"; Description: "开机自动启动 WindowPet"; GroupDescription: "系统选项:"; Flags: unchecked

[Files]
; Main Executable
Source: "..\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; Assets (Excluding unnecessary raw video_sources and media caches)
Source: "..\dist\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "video_sources\*,video_sources,*.mov,*.mp4,.media_cache\*"

; Supporting files & AI tools
Source: "..\dist\update_config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\package_registry.json"; DestDir: "{app}"; Flags: ignoreversion; Tasks: ; Languages: 
Source: "..\dist\medals.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\AGENTS.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\CLAUDE.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\AI角色制作\*"; DestDir: "{app}\AI角色制作"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppDisplayName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppDisplayName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppDisplayName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userstartup}\{#MyAppDisplayName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: startupicon

[Run]
Description: "{cm:LaunchProgram,{#StringChange(MyAppDisplayName, '&', '&&')}}"; Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent
